### ISSUE TITLE
Friendly Fire Messages

### ISSUE THREAD

**Issue by Royallle** [Neefay/BromA-Framework-A3-Addon#174]
Friendly fire messages show up when blufor/indfor players kill/wound civillian players, it also shows if a blufor Zeus, for example, remote controls an ai unit and shoots one of the other blufor players

**Comment by Coryf88** [comment]
Civilians are technically friendly. Could add a `friendly_fire_civilians` setting to override it.
To override, would add `friendly_fire_civilians = false;` in [plugin-settings.sqf](https://github.com/Neefay/BromA-A3-Framework-Mark3/blob/4df35471d7a06a59a3390b0838b5df9589d0c6bd/mission/settings/plugin-settings.sqf#L172)

I've been hesitant on fixing the remote controlled friendly fire messages, because it helps mitigate Zeus' potentially _rampaging_ and complaints about remote controlling.

**Comment by Royallle** [comment]
> Civilians are technically friendly. Could add a `friendly_fire_civilians` setting to override it.
> To override, would add `friendly_fire_civilians = false;` in [plugin-settings.sqf](https://github.com/Neefay/BromA-A3-Framework-Mark3/blob/4df35471d7a06a59a3390b0838b5df9589d0c6bd/mission/settings/plugin-settings.sqf#L172)

Seems like a good idea, this is only an issue for a very small amount of ops, but it's still annoying since there's no way to modify it.

> I've been hesitant on fixing the remote controlled friendly fire messages, because it helps mitigate Zeus' potentially _rampaging_ and complaints about remote controlling.

This is true, maybe have the message be broadcast to the admin channel only (don't know if it's possible), that way we know someone is using it, I barely remote control units and when I do it it isn't to directly kill players, only to spook/supress them but it's still a good thing to have and it kinda ruins the immersion knowing someone took that AI when the message pops up

**Comment by Coryf88** [comment]
Another issue is each "Hit" creates a separate message. E.g. A shoot B, wait 59 seconds, A shoot B, wait 1 second, "A has wounded B", wait 59 seconds, "A has wounded B".

- Message after the first hit delay, ignoring hits between. E.g. A shoot B, wait 59 seconds, A shoot B, wait 1 second, "A has wounded B".
- Message after the last hit delay. E.g. A shoot B, wait 59 seconds, A shoot B, wait 60 seconds, "A has wounded B".

I'm leaning towards the first option, since its closer to the way it currently works.

> This is true, maybe have the message be broadcast to the admin channel only (don't know if it's possible), that way we know someone is using it

It would be possible, but would add a dependency on Rhea. Another option is the log the message in the RPT either globally, clients only, or server only.

**Comment by Royallle** [comment]
> Another issue is each "Hit" creates a separate message. E.g. A shoot B, wait 59 seconds, A shoot B, wait 1 second, "A has wounded B", wait 59 seconds, "A has wounded B".
> 
> * Message after the first hit delay, ignoring hits between. E.g. A shoot B, wait 59 seconds, A shoot B, wait 1 second, "A has wounded B".
> * Message after the last hit delay. E.g. A shoot B, wait 59 seconds, A shoot B, wait 60 seconds, "A has wounded B".
> 
> I'm leaning towards the first option, since its closer to the way it currently works.
> 
> > maybe have the message be broadcast to the admin channel only (don't know if it's possible), that way we know someone is using it

Yeah first one seems better to implement.

> It would be possible, but would add a dependency on Rhea. Another option is log the message in the RPT either globally, clients only, or server only.

True, RPT server logs seems like the best idea, if we have any suspicion of some Zeus wrong doing going on then we can just check the log
